In [25]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
# 2D
b = np.array([[1,2,3],[4,5,6]])

print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
# 3D
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [29]:
# np.arange
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [30]:
# with reshape
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# np.random
np.random.random((3,4))

array([[0.20288882, 0.86312733, 0.7115526 , 0.96049902],
       [0.90795521, 0.77270184, 0.68292694, 0.41207015],
       [0.85923918, 0.82311693, 0.81086814, 0.7496807 ]])

In [34]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [35]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [36]:
a1 = np.arange(10)
a2  = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
# ndim
a3.ndim

3

In [38]:
# shape
# a2.shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
# itemsize
a3.itemsize

8

Changing Datatype

In [41]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [42]:
# scaler operations
# arithmetic
a2 * 2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [43]:
# relational
a2 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [44]:
# vector oprations
# arithmetic
# a3 / a2

Array Functions

In [49]:
# import numpy as np
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 3.,  5., 79.],
       [87., 37., 89.],
       [58.,  6., 71.]])

In [54]:
# max/min/sum/prod
# 0 > col and 1 > row
# np.max(a1,axis=1)
# np.max(a1,axis=0)
# np.sum(a1,axis=1)
np.prod(a1,axis=0)

array([ 15138.,   1110., 499201.])

In [55]:
# mean/median/std/var
np.mean(a1,axis=1)

array([29., 71., 45.])

In [57]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.14112001, -0.95892427, -0.44411267],
       [-0.82181784, -0.64353813,  0.86006941],
       [ 0.99287265, -0.2794155 ,  0.95105465]])

In [60]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [62]:
# log and exponents
# np.log(a1)
np.exp(a1)

array([[2.00855369e+01, 1.48413159e+02, 2.03828107e+34],
       [6.07603023e+37, 1.17191424e+16, 4.48961282e+38],
       [1.54553894e+25, 4.03428793e+02, 6.83767123e+30]])

In [66]:
# round/floor/ceil

# np.round(np.random.random((2,3))*100)
# np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[44., 39., 20.],
       [27., 71., 48.]])

In [67]:
a1

array([[ 3.,  5., 79.],
       [87., 37., 89.],
       [58.,  6., 71.]])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2[1,0]

np.int64(4)

In [71]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [73]:
a3[0,0]

np.int64(12)

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [108]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [109]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [110]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [111]:
for i in np.nditer(a3):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


Reshapping


In [114]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking

In [118]:
# horizonial stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [123]:
# verticaal stack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting

In [126]:
# horizontal spiliting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]