Numpy array vs Python lists

In [2]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

10.803194046020508


In [3]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

1.0030252933502197


In [4]:
4.06/0.08

50.74999999999999

In [5]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [6]:
# a = np.arange(10000000,dtype=np.int16)
# sys.getsizeof(a)

In [7]:
# a = np.arange(10000000,dtype=np.int8)
# sys.getsizeof(a)

Advanced Indexing

In [8]:
# Normal indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a[1,2]

np.int64(6)

In [10]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [11]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [12]:
# Boolean Indexing
a  = np.random.randint(1,100,24).reshape(6,4)
a

array([[12, 55, 23,  5],
       [11, 85, 56, 82],
       [27,  7, 95, 42],
       [99, 17, 19, 96],
       [97, 20,  6, 99],
       [49, 82, 41, 22]], dtype=int32)

In [13]:
# find all numbers greater than 50
a[a > 50]

array([55, 85, 56, 82, 95, 99, 96, 97, 99, 82], dtype=int32)

In [14]:
# find out even numbers
a % 2 == 0

array([[ True, False, False, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [15]:
# find all numbers greater than 50 and are even
a[(a > 50) & (a % 2 == 0)]

array([56, 82, 96, 82], dtype=int32)

In [16]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([12, 55, 23,  5, 11, 85, 82, 27, 95, 99, 17, 19, 96, 97, 20,  6, 99,
       82, 41, 22], dtype=int32)

Broadcasting

In [17]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [18]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [19]:
# More examples
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [20]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [21]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [22]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [23]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(12).reshape(4,4)
b = np.arange(12).reshape(2,2)

print(a)
print(b)

print(a+b)

ValueError: cannot reshape array of size 12 into shape (4,4)

Work with mathematical formulas

In [25]:
a = np.arange(10)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# sigmoid
def sigmoid(array):
    return 1/(1 + np.exp(-(array)))

a = np.arange(100)

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [35]:
# mean squared error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [36]:
def mse(actual,predicted):
    return np.mean((actual - predicted)**2)

mse(actual,predicted)

np.float64(480.88)

In [40]:
#  binary cross entropy
np.mean((actual - predicted)**2)

np.float64(480.88)

In [38]:
actual

array([36, 43, 38, 23, 27,  3, 44, 16, 42, 36, 14, 49, 29,  1, 30, 41, 39,
        9, 19, 47, 19,  2, 19, 47, 32], dtype=int32)

Working with missing values

In [41]:
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])