Numpy array vs Python lists

In [5]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

4.060866117477417


In [13]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.08241128921508789


In [14]:
4.06/0.08

50.74999999999999

In [15]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [ ]:
# a = np.arange(10000000,dtype=np.int16)
# sys.getsizeof(a)

20000112

In [22]:
# a = np.arange(10000000,dtype=np.int8)
# sys.getsizeof(a)

Advanced Indexing

In [40]:
# Normal indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a[1,2]

np.int64(5)

In [27]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [34]:
# Fancy Indexing

a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [41]:
# Boolean Indexing
a  = np.random.randint(1,100,24).reshape(6,4)
a

array([[38, 56, 16, 22],
       [87, 33, 85, 84],
       [25, 49, 12,  8],
       [62, 26, 34, 37],
       [24, 56, 14, 16],
       [81, 19, 71,  4]], dtype=int32)

In [42]:
# find all numbers greater than 50
a[a > 50]

array([56, 87, 85, 84, 62, 56, 81, 71], dtype=int32)

In [43]:
# find out even numbers
a % 2 == 0

array([[ True,  True,  True,  True],
       [False, False, False,  True],
       [False, False,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [44]:
# find all numbers greater than 50 and are even
a[(a > 50) & (a % 2 == 0)]

array([56, 84, 62, 56], dtype=int32)

In [45]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([38, 16, 22, 87, 33, 85, 25, 12,  8, 62, 26, 34, 37, 24, 16, 81, 19,
       71,  4], dtype=int32)

Broadcasting

In [47]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [50]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [57]:
# More examples
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [58]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [59]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [60]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [61]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [62]:
a = np.arange(12).reshape(4,4)
b = np.arange(12).reshape(2,2)

print(a)
print(b)

print(a+b)

ValueError: cannot reshape array of size 12 into shape (4,4)