np.sort

In [46]:
# core
import numpy as np
a = np.random.randint(1,100,15)
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [47]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[28, 40, 19, 38],
       [80, 52, 24,  8],
       [49, 14, 20, 68],
       [27,  4,  8, 12],
       [81, 18, 70, 53],
       [11, 44, 40, 60]], dtype=int32)

In [48]:
np.sort(a)[::-1]

array([97, 95, 52, 52, 43, 42, 39, 36, 24, 23, 19, 12,  8,  7,  3],
      dtype=int32)

In [49]:
np.sort(b,axis=0)

array([[11,  4,  8,  8],
       [27, 14, 19, 12],
       [28, 18, 20, 38],
       [49, 40, 24, 53],
       [80, 44, 40, 60],
       [81, 52, 70, 68]], dtype=int32)

np.append

In [50]:
# core
np.append(a,200)

array([ 24,  39,  52,  23,  12,   8,  36,  42,   3,  95,  19,   7,  52,
        97,  43, 200])

In [51]:
b

array([[28, 40, 19, 38],
       [80, 52, 24,  8],
       [49, 14, 20, 68],
       [27,  4,  8, 12],
       [81, 18, 70, 53],
       [11, 44, 40, 60]], dtype=int32)

In [52]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[28., 40., 19., 38.,  1.],
       [80., 52., 24.,  8.,  1.],
       [49., 14., 20., 68.,  1.],
       [27.,  4.,  8., 12.,  1.],
       [81., 18., 70., 53.,  1.],
       [11., 44., 40., 60.,  1.]])

np.concatenate

In [53]:
# core
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [54]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

In [56]:
# core

e = np.array([1,2,3,3,3,4,5,6,6,6,7,7,3])

In [57]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

np.expand_dims

In [58]:
# core

a.shape

(15,)

In [59]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [60]:
np.expand_dims(a,axis=1)

array([[24],
       [39],
       [52],
       [23],
       [12],
       [ 8],
       [36],
       [42],
       [ 3],
       [95],
       [19],
       [ 7],
       [52],
       [97],
       [43]], dtype=int32)

np.where

In [61]:
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [62]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  9, 12, 13]),)

In [63]:
# replace all values > 50 with 0
# np.where(a>50.True,False)
np.where(a>50,0,a)

array([24, 39,  0, 23, 12,  8, 36, 42,  3,  0, 19,  7,  0,  0, 43],
      dtype=int32)

In [64]:
np.where(a%2 == 0,0,a)

array([ 0, 39,  0, 23,  0,  0,  0,  0,  3, 95, 19,  7,  0, 97, 43],
      dtype=int32)

np.argmax

In [65]:
# code
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [66]:
np.argmax(a)

np.int64(13)

In [67]:
b

array([[28, 40, 19, 38],
       [80, 52, 24,  8],
       [49, 14, 20, 68],
       [27,  4,  8, 12],
       [81, 18, 70, 53],
       [11, 44, 40, 60]], dtype=int32)

In [68]:
np.argmax(b,axis=0)

array([4, 1, 4, 2])

In [69]:
np.argmax(b,axis=1)

array([1, 0, 3, 0, 0, 3])

In [70]:
# min
np.argmin(a)

np.int64(8)

np.cumsum

In [71]:
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [72]:
np.cumsum(a)

array([ 24,  63, 115, 138, 150, 158, 194, 236, 239, 334, 353, 360, 412,
       509, 552])

In [73]:
b

array([[28, 40, 19, 38],
       [80, 52, 24,  8],
       [49, 14, 20, 68],
       [27,  4,  8, 12],
       [81, 18, 70, 53],
       [11, 44, 40, 60]], dtype=int32)

In [74]:
np.cumsum(b,axis=1)

array([[ 28,  68,  87, 125],
       [ 80, 132, 156, 164],
       [ 49,  63,  83, 151],
       [ 27,  31,  39,  51],
       [ 81,  99, 169, 222],
       [ 11,  55,  95, 155]])

In [75]:
np.cumsum(b)

array([ 28,  68,  87, 125, 205, 257, 281, 289, 338, 352, 372, 440, 467,
       471, 479, 491, 572, 590, 660, 713, 724, 768, 808, 868])

In [76]:
np.cumsum(a)

array([ 24,  63, 115, 138, 150, 158, 194, 236, 239, 334, 353, 360, 412,
       509, 552])

In [77]:
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

np.percentile

In [78]:
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [79]:
np.percentile(a,50)

np.float64(36.0)

np.histogram

In [80]:
# code
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [82]:
np.histogram(a,bins=[0,50,100])

(array([11,  4]), array([  0,  50, 100]))

np.corrcoef

In [83]:
salary = np.array([20000,40000,25000,15000,60000])
experience = np.array([1,3,3,4,2])

np.corrcoef(salary,experience)

array([[ 1.        , -0.25251769],
       [-0.25251769,  1.        ]])

np.isin

In [84]:
# code
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [86]:
items = [10,53,43,26,56,8,6,3,29]

# np.isin(a,items)
a[np.isin(a,items)]

array([ 8,  3, 43], dtype=int32)

np.flip

In [87]:
# code
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [88]:
np.flip(a)

array([43, 97, 52,  7, 19, 95,  3, 42, 36,  8, 12, 23, 52, 39, 24],
      dtype=int32)

In [90]:
b

array([[28, 40, 19, 38],
       [80, 52, 24,  8],
       [49, 14, 20, 68],
       [27,  4,  8, 12],
       [81, 18, 70, 53],
       [11, 44, 40, 60]], dtype=int32)

In [91]:
np.flip(b,axis=0)

array([[11, 44, 40, 60],
       [81, 18, 70, 53],
       [27,  4,  8, 12],
       [49, 14, 20, 68],
       [80, 52, 24,  8],
       [28, 40, 19, 38]], dtype=int32)

In [92]:
np.flip(b,axis=1)

array([[38, 19, 40, 28],
       [ 8, 24, 52, 80],
       [68, 20, 14, 49],
       [12,  8,  4, 27],
       [53, 70, 18, 81],
       [60, 40, 44, 11]], dtype=int32)

np.put

In [93]:
# code
a

array([24, 39, 52, 23, 12,  8, 36, 42,  3, 95, 19,  7, 52, 97, 43],
      dtype=int32)

In [94]:
np.put(a,[0,1],[110,530])

np.delete

In [95]:
np.delete(a,[0,2,4])

array([530,  23,   8,  36,  42,   3,  95,  19,   7,  52,  97,  43],
      dtype=int32)

Set functions
.np.union1d
.np.intersect1d
.np.setdiff1d
.np.setxor1d
.np.in1d

In [97]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])