np.sort

In [4]:
# core
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 94, 62, 42, 46, 33, 57, 34, 24, 90, 84, 42, 92,  7, 34],
      dtype=int32)

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[92, 21, 10, 27],
       [89, 48, 34, 94],
       [18, 38, 76, 27],
       [ 9, 21, 37, 37],
       [53, 79, 71, 32],
       [83, 70, 54, 29]], dtype=int32)

In [10]:
np.sort(a)[::-1]

array([94, 92, 90, 86, 84, 62, 57, 46, 42, 42, 34, 34, 33, 24,  7],
      dtype=int32)

In [9]:
np.sort(b,axis=0)

array([[ 9, 21, 10, 27],
       [18, 21, 34, 27],
       [53, 38, 37, 29],
       [83, 48, 54, 32],
       [89, 70, 71, 37],
       [92, 79, 76, 94]], dtype=int32)

np.append

In [11]:
# core
np.append(a,200)

array([ 86,  94,  62,  42,  46,  33,  57,  34,  24,  90,  84,  42,  92,
         7,  34, 200])

In [12]:
b

array([[92, 21, 10, 27],
       [89, 48, 34, 94],
       [18, 38, 76, 27],
       [ 9, 21, 37, 37],
       [53, 79, 71, 32],
       [83, 70, 54, 29]], dtype=int32)

In [13]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[92., 21., 10., 27.,  1.],
       [89., 48., 34., 94.,  1.],
       [18., 38., 76., 27.,  1.],
       [ 9., 21., 37., 37.,  1.],
       [53., 79., 71., 32.,  1.],
       [83., 70., 54., 29.,  1.]])

np.concatenate

In [14]:
# core
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique